export class ActivityTypes {
  // Lead activities
  static LEAD_CREATED = 'LEAD_CREATED';
  static LEAD_UPDATED = 'LEAD_UPDATED';
  static LEAD_DELETED = 'LEAD_DELETED';
  static LEAD_CONVERTED = 'LEAD_CONVERTED';

  // Contact activities
  static CONTACT_CREATED = 'CONTACT_CREATED';
  static CONTACT_UPDATED = 'CONTACT_UPDATED';
  static CONTACT_DELETED = 'CONTACT_DELETED';

  // Company activities
  static COMPANY_CREATED = 'COMPANY_CREATED';
  static COMPANY_UPDATED = 'COMPANY_UPDATED';
  static COMPANY_DELETED = 'COMPANY_DELETED';

  // Deal activities
  static DEAL_CREATED = 'DEAL_CREATED';
  static DEAL_UPDATED = 'DEAL_UPDATED';
  static DEAL_DELETED = 'DEAL_DELETED';
  static DEAL_STAGE_CHANGED = 'DEAL_STAGE_CHANGED';
  static DEAL_WON = 'DEAL_WON';
  static DEAL_LOST = 'DEAL_LOST';

  // Task activities
  static TASK_CREATED = 'TASK_CREATED';
  static TASK_UPDATED = 'TASK_UPDATED';
  static TASK_COMPLETED = 'TASK_COMPLETED';
  static TASK_REOPENED = 'TASK_REOPENED';
  static TASK_DELETED = 'TASK_DELETED';

  // Meeting activities
  static MEETING_SCHEDULED = 'MEETING_SCHEDULED';
  static MEETING_UPDATED = 'MEETING_UPDATED';
  static MEETING_CANCELLED = 'MEETING_CANCELLED';
  static MEETING_COMPLETED = 'MEETING_COMPLETED';

  // Calendar activities
  static CALENDAR_EVENT_ADDED = 'CALENDAR_EVENT_ADDED';
  static CALENDAR_EVENT_UPDATED = 'CALENDAR_EVENT_UPDATED';
  static CALENDAR_EVENT_DELETED = 'CALENDAR_EVENT_DELETED';

  // Campaign activities
  static CAMPAIGN_CREATED = 'CAMPAIGN_CREATED';
  static CAMPAIGN_UPDATED = 'CAMPAIGN_UPDATED';
  static CAMPAIGN_DELETED = 'CAMPAIGN_DELETED';

  // Product & Quote activities (Phase 13C Prep)
  static PRODUCT_CREATED = 'PRODUCT_CREATED';
  static PRODUCT_UPDATED = 'PRODUCT_UPDATED';
  static QUOTE_CREATED = 'QUOTE_CREATED';
  static QUOTE_SUBMITTED = 'QUOTE_SUBMITTED';
  static QUOTE_APPROVED = 'QUOTE_APPROVED';
  static QUOTE_REJECTED = 'QUOTE_REJECTED';

  // Document activities
  static DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED';
  static DOCUMENT_DELETED = 'DOCUMENT_DELETED';
}

export const ACTIVITY_TYPES = {
  LEAD_CREATED: 'LEAD_CREATED',
  LEAD_UPDATED: 'LEAD_UPDATED',
  LEAD_DELETED: 'LEAD_DELETED',
  LEAD_CONVERTED: 'LEAD_CONVERTED',
  CONTACT_CREATED: 'CONTACT_CREATED',
  CONTACT_UPDATED: 'CONTACT_UPDATED',
  CONTACT_DELETED: 'CONTACT_DELETED',
  COMPANY_CREATED: 'COMPANY_CREATED',
  COMPANY_UPDATED: 'COMPANY_UPDATED',
  COMPANY_DELETED: 'COMPANY_DELETED',
  DEAL_CREATED: 'DEAL_CREATED',
  DEAL_UPDATED: 'DEAL_UPDATED',
  DEAL_DELETED: 'DEAL_DELETED',
  DEAL_STAGE_CHANGED: 'DEAL_STAGE_CHANGED',
  DEAL_WON: 'DEAL_WON',
  DEAL_LOST: 'DEAL_LOST',
  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_REOPENED: 'TASK_REOPENED',
  TASK_DELETED: 'TASK_DELETED',
  MEETING_SCHEDULED: 'MEETING_SCHEDULED',
  MEETING_UPDATED: 'MEETING_UPDATED',
  MEETING_CANCELLED: 'MEETING_CANCELLED',
  MEETING_COMPLETED: 'MEETING_COMPLETED',
  CALENDAR_EVENT_ADDED: 'CALENDAR_EVENT_ADDED',
  CALENDAR_EVENT_UPDATED: 'CALENDAR_EVENT_UPDATED',
  CALENDAR_EVENT_DELETED: 'CALENDAR_EVENT_DELETED',
  CAMPAIGN_CREATED: 'CAMPAIGN_CREATED',
  CAMPAIGN_UPDATED: 'CAMPAIGN_UPDATED',
  CAMPAIGN_DELETED: 'CAMPAIGN_DELETED',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  QUOTE_CREATED: 'QUOTE_CREATED',
  QUOTE_SUBMITTED: 'QUOTE_SUBMITTED',
  QUOTE_APPROVED: 'QUOTE_APPROVED',
  QUOTE_REJECTED: 'QUOTE_REJECTED',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_DELETED: 'DOCUMENT_DELETED'
};
